### ISSUE TITLE
Firebase Error

### ISSUE THREAD

**Issue by KillerRoi** [kiipy/application-bot#1]
`(node:8212) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: The project discord-bot-2047a does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=discord-bot-2047a to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.
    at Object.callErrorFromStatus (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\client.js:327:49)
    at Object.onReceiveStatus (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:305:181)
    at Http2CallStream.outputStatus (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\call-stream.js:117:74)
    at Http2CallStream.maybeOutputStatus (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\call-stream.js:156:22)
    at Http2CallStream.endCall (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\call-stream.js:142:18)
    at Http2CallStream.handleTrailers (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@grpc\grpc-js\build\src\call-stream.js:274:14)
    at ClientHttp2Stream.emit (events.js:209:13)
    at emit (internal/http2/core.js:277:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Caused by: Error
    at Firestore.getAll (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@google-cloud\firestore\build\src\index.js:755:23)
    at DocumentReference.get (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\@google-cloud\firestore\build\src\reference.js:199:32)
    at Client.<anonymous> (D:\Mr.King\Downloads\Compressed\application-bot-master\commands.js:24:34)
    at Client.emit (events.js:214:15)
    at MessageCreateAction.handle (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\Mr.King\Downloads\Compressed\application-bot-master\node_modules\ws\lib\event-target.js:125:16)
(node:8212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by kiip1** [comment]
You need to create a Firebase project at http://console.cloud.google.com.

If you've done that, create a Cloud Firestore database.

After that, you need to make a service account and download the private key and paste it into `firebase.json`.

If you have any other problems, do not worry to ask.
