### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by Liqxid** [kiipy/application-bot#2]
I have gotten the firbase stuff and put it in firebase.json but now i get
(node:25693) UnhandledPromiseRejectionWarning: Error: 9 FAILED_PRECONDITION: The Cloud Firestore API is not available for Datastore Mode projects.
    at Object.callErrorFromStatus (/home/pi/application-bot/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/pi/application-bot/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/home/pi/application-bot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at /home/pi/application-bot/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Caused by: Error
    at Firestore.getAll (/home/pi/application-bot/node_modules/@google-cloud/firestore/build/src/index.js:755:23)
    at DocumentReference.get (/home/pi/application-bot/node_modules/@google-cloud/firestore/build/src/reference.js:201:32)
    at Client.<anonymous> (/home/pi/application-bot/commands.js:24:34)
    at Client.emit (events.js:326:22)
    at MessageCreateAction.handle (/home/pi/application-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/pi/application-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/pi/application-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/pi/application-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/pi/application-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/pi/application-bot/node_modules/ws/lib/event-target.js:125:16)
(node:25693) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by Liqxid** [comment]
nevermind i fixed it
